services:
  _defaults:
    public: true

  prestashop.blockwishlist.controller.admin.ajax:
    class: PrestaShop\Module\BlockWishList\Controller\AdminAjaxPrestashopWishlistController
    arguments:
      - '@doctrine.cache.provider'
